#!/usr/bin/env python3
"""Generate the cosmo errno-compat headers in cosmo/compat/cosmo_compat/.

Under Cosmopolitan Libc, errno constants are runtime symbols (extern const
int) whose values depend on the host OS, so they cannot appear in constant
expressions (enum initializers in boost/system and boost/asio). The generated
headers provide:

  cosmo_errno_compat.h      runtime translation Linux-sentinel -> native value
  cosmo_errno_linux_push.h  push_macro + redefine errno macros to Linux values
  cosmo_errno_linux_pop.h   pop_macro (restores the symbolic definitions)

The sentinel values are the canonical Linux x86_64 errno numbers. They exist
only at compile time inside the patched Boost headers; every place where the
enums are turned into error_code/error_condition values translates back to
the host's native errno via cosmo_compat::native_errno().
"""

import os

# (macro, linux x86_64 value). EWOULDBLOCK==EAGAIN and EOPNOTSUPP==ENOTSUP on
# Linux; the duplicates are resolved to a single table entry below.
ERRNOS = [
    ("EPERM", 1), ("ENOENT", 2), ("ESRCH", 3), ("EINTR", 4), ("EIO", 5),
    ("ENXIO", 6), ("E2BIG", 7), ("ENOEXEC", 8), ("EBADF", 9), ("ECHILD", 10),
    ("EAGAIN", 11), ("ENOMEM", 12), ("EACCES", 13), ("EFAULT", 14),
    ("ENOTBLK", 15), ("EBUSY", 16), ("EEXIST", 17), ("EXDEV", 18),
    ("ENODEV", 19), ("ENOTDIR", 20), ("EISDIR", 21), ("EINVAL", 22),
    ("ENFILE", 23), ("EMFILE", 24), ("ENOTTY", 25), ("ETXTBSY", 26),
    ("EFBIG", 27), ("ENOSPC", 28), ("ESPIPE", 29), ("EROFS", 30),
    ("EMLINK", 31), ("EPIPE", 32), ("EDOM", 33), ("ERANGE", 34),
    ("EDEADLK", 35), ("ENAMETOOLONG", 36), ("ENOLCK", 37), ("ENOSYS", 38),
    ("ENOTEMPTY", 39), ("ELOOP", 40), ("EWOULDBLOCK", 11), ("ENOMSG", 42),
    ("EIDRM", 43), ("ENOSTR", 60), ("ENODATA", 61), ("ETIME", 62),
    ("ENOSR", 63), ("ENOLINK", 67), ("EPROTO", 71), ("EBADMSG", 74),
    ("EOVERFLOW", 75), ("EILSEQ", 84), ("ENOTSOCK", 88), ("EDESTADDRREQ", 89),
    ("EMSGSIZE", 90), ("EPROTOTYPE", 91), ("ENOPROTOOPT", 92),
    ("EPROTONOSUPPORT", 93), ("ESOCKTNOSUPPORT", 94), ("EOPNOTSUPP", 95),
    ("ENOTSUP", 95), ("EPFNOSUPPORT", 96), ("EAFNOSUPPORT", 97),
    ("EADDRINUSE", 98), ("EADDRNOTAVAIL", 99), ("ENETDOWN", 100),
    ("ENETUNREACH", 101), ("ENETRESET", 102), ("ECONNABORTED", 103),
    ("ECONNRESET", 104), ("ENOBUFS", 105), ("EISCONN", 106),
    ("ENOTCONN", 107), ("ESHUTDOWN", 108), ("ETOOMANYREFS", 109),
    ("ETIMEDOUT", 110), ("ECONNREFUSED", 111), ("EHOSTDOWN", 112),
    ("EHOSTUNREACH", 113), ("EALREADY", 114), ("EINPROGRESS", 115),
    ("ESTALE", 116), ("EDQUOT", 122), ("ECANCELED", 125), ("EOWNERDEAD", 130),
    ("ENOTRECOVERABLE", 131),
]

OUT = os.path.join(os.path.dirname(__file__), "compat", "cosmo_compat")

WARNING = "// GENERATED by cosmo/gen_errno_compat.py — do not edit by hand.\n"


def gen_compat():
    # one entry per distinct linux value, keep the first macro for it
    seen = {}
    for macro, val in ERRNOS:
        seen.setdefault(val, macro)
    entries = "\n".join(
        f"        {{{val}, &{macro}}}," for val, macro in sorted(seen.items())
    )
    return f"""{WARNING}// Runtime translation of Linux-sentinel errno values (used at compile time in
// the patched boost/system and boost/asio headers) to this host's native
// errno values. Must be included while the real <errno.h> macros (symbolic
// under Cosmopolitan) are in effect, i.e. BEFORE cosmo_errno_linux_push.h.
#ifndef COSMO_COMPAT_COSMO_ERRNO_COMPAT_H
#define COSMO_COMPAT_COSMO_ERRNO_COMPAT_H
#ifdef __COSMOPOLITAN__

#include <errno.h>

namespace cosmo_compat {{

inline int native_errno(int linuxSentinel) noexcept {{
    struct Entry {{
        int linuxValue;
        const int* nativeValue;
    }};
    static const Entry table[] = {{
{entries}
    }};
    for (const Entry& e : table) {{
        if (e.linuxValue == linuxSentinel) return *e.nativeValue;
    }}
    return linuxSentinel;
}}

}}  // namespace cosmo_compat

#endif  // __COSMOPOLITAN__
#endif  // COSMO_COMPAT_COSMO_ERRNO_COMPAT_H
"""


def gen_push():
    body = "\n".join(
        f'#pragma push_macro("{macro}")\n#undef {macro}\n#define {macro} {val}'
        for macro, val in ERRNOS
    )
    return f"""{WARNING}// Temporarily redefine the (symbolic) Cosmopolitan errno macros to Linux
// x86_64 numeric sentinels so they can be used in constant expressions.
// Every inclusion MUST be balanced by cosmo_errno_linux_pop.h, and
// cosmo_errno_compat.h must already have been included (it captures the
// real symbol addresses).
#ifdef __COSMOPOLITAN__
#ifndef COSMO_COMPAT_COSMO_ERRNO_COMPAT_H
#error "include cosmo_compat/cosmo_errno_compat.h before the push header"
#endif
{body}
#endif  // __COSMOPOLITAN__
"""


def gen_pop():
    body = "\n".join(f'#pragma pop_macro("{macro}")' for macro, _ in ERRNOS)
    return f"""{WARNING}// Restores the errno macros redefined by cosmo_errno_linux_push.h.
#ifdef __COSMOPOLITAN__
{body}
#endif  // __COSMOPOLITAN__
"""


def main():
    os.makedirs(OUT, exist_ok=True)
    for name, content in [
        ("cosmo_errno_compat.h", gen_compat()),
        ("cosmo_errno_linux_push.h", gen_push()),
        ("cosmo_errno_linux_pop.h", gen_pop()),
    ]:
        with open(os.path.join(OUT, name), "w") as f:
            f.write(content)
        print(f"wrote {os.path.join(OUT, name)}")


if __name__ == "__main__":
    main()
