// GENERATED by cosmo/gen_errno_compat.py — do not edit by hand.
// Temporarily redefine the (symbolic) Cosmopolitan errno macros to Linux
// x86_64 numeric sentinels so they can be used in constant expressions.
// Every inclusion MUST be balanced by cosmo_errno_linux_pop.h, and
// cosmo_errno_compat.h must already have been included (it captures the
// real symbol addresses).
#ifdef __COSMOPOLITAN__
#ifndef COSMO_COMPAT_COSMO_ERRNO_COMPAT_H
#error "include cosmo_compat/cosmo_errno_compat.h before the push header"
#endif
#pragma push_macro("EPERM")
#undef EPERM
#define EPERM 1
#pragma push_macro("ENOENT")
#undef ENOENT
#define ENOENT 2
#pragma push_macro("ESRCH")
#undef ESRCH
#define ESRCH 3
#pragma push_macro("EINTR")
#undef EINTR
#define EINTR 4
#pragma push_macro("EIO")
#undef EIO
#define EIO 5
#pragma push_macro("ENXIO")
#undef ENXIO
#define ENXIO 6
#pragma push_macro("E2BIG")
#undef E2BIG
#define E2BIG 7
#pragma push_macro("ENOEXEC")
#undef ENOEXEC
#define ENOEXEC 8
#pragma push_macro("EBADF")
#undef EBADF
#define EBADF 9
#pragma push_macro("ECHILD")
#undef ECHILD
#define ECHILD 10
#pragma push_macro("EAGAIN")
#undef EAGAIN
#define EAGAIN 11
#pragma push_macro("ENOMEM")
#undef ENOMEM
#define ENOMEM 12
#pragma push_macro("EACCES")
#undef EACCES
#define EACCES 13
#pragma push_macro("EFAULT")
#undef EFAULT
#define EFAULT 14
#pragma push_macro("ENOTBLK")
#undef ENOTBLK
#define ENOTBLK 15
#pragma push_macro("EBUSY")
#undef EBUSY
#define EBUSY 16
#pragma push_macro("EEXIST")
#undef EEXIST
#define EEXIST 17
#pragma push_macro("EXDEV")
#undef EXDEV
#define EXDEV 18
#pragma push_macro("ENODEV")
#undef ENODEV
#define ENODEV 19
#pragma push_macro("ENOTDIR")
#undef ENOTDIR
#define ENOTDIR 20
#pragma push_macro("EISDIR")
#undef EISDIR
#define EISDIR 21
#pragma push_macro("EINVAL")
#undef EINVAL
#define EINVAL 22
#pragma push_macro("ENFILE")
#undef ENFILE
#define ENFILE 23
#pragma push_macro("EMFILE")
#undef EMFILE
#define EMFILE 24
#pragma push_macro("ENOTTY")
#undef ENOTTY
#define ENOTTY 25
#pragma push_macro("ETXTBSY")
#undef ETXTBSY
#define ETXTBSY 26
#pragma push_macro("EFBIG")
#undef EFBIG
#define EFBIG 27
#pragma push_macro("ENOSPC")
#undef ENOSPC
#define ENOSPC 28
#pragma push_macro("ESPIPE")
#undef ESPIPE
#define ESPIPE 29
#pragma push_macro("EROFS")
#undef EROFS
#define EROFS 30
#pragma push_macro("EMLINK")
#undef EMLINK
#define EMLINK 31
#pragma push_macro("EPIPE")
#undef EPIPE
#define EPIPE 32
#pragma push_macro("EDOM")
#undef EDOM
#define EDOM 33
#pragma push_macro("ERANGE")
#undef ERANGE
#define ERANGE 34
#pragma push_macro("EDEADLK")
#undef EDEADLK
#define EDEADLK 35
#pragma push_macro("ENAMETOOLONG")
#undef ENAMETOOLONG
#define ENAMETOOLONG 36
#pragma push_macro("ENOLCK")
#undef ENOLCK
#define ENOLCK 37
#pragma push_macro("ENOSYS")
#undef ENOSYS
#define ENOSYS 38
#pragma push_macro("ENOTEMPTY")
#undef ENOTEMPTY
#define ENOTEMPTY 39
#pragma push_macro("ELOOP")
#undef ELOOP
#define ELOOP 40
#pragma push_macro("EWOULDBLOCK")
#undef EWOULDBLOCK
#define EWOULDBLOCK 11
#pragma push_macro("ENOMSG")
#undef ENOMSG
#define ENOMSG 42
#pragma push_macro("EIDRM")
#undef EIDRM
#define EIDRM 43
#pragma push_macro("ENOSTR")
#undef ENOSTR
#define ENOSTR 60
#pragma push_macro("ENODATA")
#undef ENODATA
#define ENODATA 61
#pragma push_macro("ETIME")
#undef ETIME
#define ETIME 62
#pragma push_macro("ENOSR")
#undef ENOSR
#define ENOSR 63
#pragma push_macro("ENOLINK")
#undef ENOLINK
#define ENOLINK 67
#pragma push_macro("EPROTO")
#undef EPROTO
#define EPROTO 71
#pragma push_macro("EBADMSG")
#undef EBADMSG
#define EBADMSG 74
#pragma push_macro("EOVERFLOW")
#undef EOVERFLOW
#define EOVERFLOW 75
#pragma push_macro("EILSEQ")
#undef EILSEQ
#define EILSEQ 84
#pragma push_macro("ENOTSOCK")
#undef ENOTSOCK
#define ENOTSOCK 88
#pragma push_macro("EDESTADDRREQ")
#undef EDESTADDRREQ
#define EDESTADDRREQ 89
#pragma push_macro("EMSGSIZE")
#undef EMSGSIZE
#define EMSGSIZE 90
#pragma push_macro("EPROTOTYPE")
#undef EPROTOTYPE
#define EPROTOTYPE 91
#pragma push_macro("ENOPROTOOPT")
#undef ENOPROTOOPT
#define ENOPROTOOPT 92
#pragma push_macro("EPROTONOSUPPORT")
#undef EPROTONOSUPPORT
#define EPROTONOSUPPORT 93
#pragma push_macro("ESOCKTNOSUPPORT")
#undef ESOCKTNOSUPPORT
#define ESOCKTNOSUPPORT 94
#pragma push_macro("EOPNOTSUPP")
#undef EOPNOTSUPP
#define EOPNOTSUPP 95
#pragma push_macro("ENOTSUP")
#undef ENOTSUP
#define ENOTSUP 95
#pragma push_macro("EPFNOSUPPORT")
#undef EPFNOSUPPORT
#define EPFNOSUPPORT 96
#pragma push_macro("EAFNOSUPPORT")
#undef EAFNOSUPPORT
#define EAFNOSUPPORT 97
#pragma push_macro("EADDRINUSE")
#undef EADDRINUSE
#define EADDRINUSE 98
#pragma push_macro("EADDRNOTAVAIL")
#undef EADDRNOTAVAIL
#define EADDRNOTAVAIL 99
#pragma push_macro("ENETDOWN")
#undef ENETDOWN
#define ENETDOWN 100
#pragma push_macro("ENETUNREACH")
#undef ENETUNREACH
#define ENETUNREACH 101
#pragma push_macro("ENETRESET")
#undef ENETRESET
#define ENETRESET 102
#pragma push_macro("ECONNABORTED")
#undef ECONNABORTED
#define ECONNABORTED 103
#pragma push_macro("ECONNRESET")
#undef ECONNRESET
#define ECONNRESET 104
#pragma push_macro("ENOBUFS")
#undef ENOBUFS
#define ENOBUFS 105
#pragma push_macro("EISCONN")
#undef EISCONN
#define EISCONN 106
#pragma push_macro("ENOTCONN")
#undef ENOTCONN
#define ENOTCONN 107
#pragma push_macro("ESHUTDOWN")
#undef ESHUTDOWN
#define ESHUTDOWN 108
#pragma push_macro("ETOOMANYREFS")
#undef ETOOMANYREFS
#define ETOOMANYREFS 109
#pragma push_macro("ETIMEDOUT")
#undef ETIMEDOUT
#define ETIMEDOUT 110
#pragma push_macro("ECONNREFUSED")
#undef ECONNREFUSED
#define ECONNREFUSED 111
#pragma push_macro("EHOSTDOWN")
#undef EHOSTDOWN
#define EHOSTDOWN 112
#pragma push_macro("EHOSTUNREACH")
#undef EHOSTUNREACH
#define EHOSTUNREACH 113
#pragma push_macro("EALREADY")
#undef EALREADY
#define EALREADY 114
#pragma push_macro("EINPROGRESS")
#undef EINPROGRESS
#define EINPROGRESS 115
#pragma push_macro("ESTALE")
#undef ESTALE
#define ESTALE 116
#pragma push_macro("EDQUOT")
#undef EDQUOT
#define EDQUOT 122
#pragma push_macro("ECANCELED")
#undef ECANCELED
#define ECANCELED 125
#pragma push_macro("EOWNERDEAD")
#undef EOWNERDEAD
#define EOWNERDEAD 130
#pragma push_macro("ENOTRECOVERABLE")
#undef ENOTRECOVERABLE
#define ENOTRECOVERABLE 131
#endif  // __COSMOPOLITAN__
