// GENERATED by cosmo/gen_errno_compat.py — do not edit by hand.
// Runtime translation of Linux-sentinel errno values (used at compile time in
// the patched boost/system and boost/asio headers) to this host's native
// errno values. Must be included while the real <errno.h> macros (symbolic
// under Cosmopolitan) are in effect, i.e. BEFORE cosmo_errno_linux_push.h.
#ifndef COSMO_COMPAT_COSMO_ERRNO_COMPAT_H
#define COSMO_COMPAT_COSMO_ERRNO_COMPAT_H
#ifdef __COSMOPOLITAN__

#include <errno.h>

namespace cosmo_compat {

inline int native_errno(int linuxSentinel) noexcept {
    struct Entry {
        int linuxValue;
        const int* nativeValue;
    };
    static const Entry table[] = {
        {1, &EPERM},
        {2, &ENOENT},
        {3, &ESRCH},
        {4, &EINTR},
        {5, &EIO},
        {6, &ENXIO},
        {7, &E2BIG},
        {8, &ENOEXEC},
        {9, &EBADF},
        {10, &ECHILD},
        {11, &EAGAIN},
        {12, &ENOMEM},
        {13, &EACCES},
        {14, &EFAULT},
        {15, &ENOTBLK},
        {16, &EBUSY},
        {17, &EEXIST},
        {18, &EXDEV},
        {19, &ENODEV},
        {20, &ENOTDIR},
        {21, &EISDIR},
        {22, &EINVAL},
        {23, &ENFILE},
        {24, &EMFILE},
        {25, &ENOTTY},
        {26, &ETXTBSY},
        {27, &EFBIG},
        {28, &ENOSPC},
        {29, &ESPIPE},
        {30, &EROFS},
        {31, &EMLINK},
        {32, &EPIPE},
        {33, &EDOM},
        {34, &ERANGE},
        {35, &EDEADLK},
        {36, &ENAMETOOLONG},
        {37, &ENOLCK},
        {38, &ENOSYS},
        {39, &ENOTEMPTY},
        {40, &ELOOP},
        {42, &ENOMSG},
        {43, &EIDRM},
        {60, &ENOSTR},
        {61, &ENODATA},
        {62, &ETIME},
        {63, &ENOSR},
        {67, &ENOLINK},
        {71, &EPROTO},
        {74, &EBADMSG},
        {75, &EOVERFLOW},
        {84, &EILSEQ},
        {88, &ENOTSOCK},
        {89, &EDESTADDRREQ},
        {90, &EMSGSIZE},
        {91, &EPROTOTYPE},
        {92, &ENOPROTOOPT},
        {93, &EPROTONOSUPPORT},
        {94, &ESOCKTNOSUPPORT},
        {95, &EOPNOTSUPP},
        {96, &EPFNOSUPPORT},
        {97, &EAFNOSUPPORT},
        {98, &EADDRINUSE},
        {99, &EADDRNOTAVAIL},
        {100, &ENETDOWN},
        {101, &ENETUNREACH},
        {102, &ENETRESET},
        {103, &ECONNABORTED},
        {104, &ECONNRESET},
        {105, &ENOBUFS},
        {106, &EISCONN},
        {107, &ENOTCONN},
        {108, &ESHUTDOWN},
        {109, &ETOOMANYREFS},
        {110, &ETIMEDOUT},
        {111, &ECONNREFUSED},
        {112, &EHOSTDOWN},
        {113, &EHOSTUNREACH},
        {114, &EALREADY},
        {115, &EINPROGRESS},
        {116, &ESTALE},
        {122, &EDQUOT},
        {125, &ECANCELED},
        {130, &EOWNERDEAD},
        {131, &ENOTRECOVERABLE},
    };
    for (const Entry& e : table) {
        if (e.linuxValue == linuxSentinel) return *e.nativeValue;
    }
    return linuxSentinel;
}

}  // namespace cosmo_compat

#endif  // __COSMOPOLITAN__
#endif  // COSMO_COMPAT_COSMO_ERRNO_COMPAT_H
